import uuid
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from graph.state import MosaicState, SignalOutput
from config.settings import settings
from config.logging_config import setup_logging
from dotenv import load_dotenv
load_dotenv()

logger = setup_logging(__name__)

llm = ChatGroq(model=settings.chat_model, temperature=0.1)


async def supervisor_route(state: MosaicState) -> dict:
    run_id = str(uuid.uuid4())
    logger.info(
        f"Supervisor routing | run_id = {run_id} | task = {state.get('task', '')[:80]}")

    return {
        "run_id": run_id,
        "agents_activated": [],
        "signals": [],
        "run_complete": False,
        "error_log": []
    }


async def supervisor_compile(state: MosaicState) -> dict:
    signals = state.get("signals", [])
    agents_activated = state.get("agents_activated", [])
    task = state.get("task", "")

    logger.info(
        f"Supervisor compiling brief | signals = {len(signals)} | agents_activated={len(agents_activated)}")

    if not signals:
        logger.info("No signals found - returning clean brief")
        return {
            "final_brief": (
                "**EXECUTIVE SUMMARY:**Analysis complete. No significant research integrity signals were detected for the specified task and study set."
            ),
            "run_complete": True,
            "agents_activated": agents_activated,
        }

    high_confidence_signals = [
        s for s in signals if s.get("confidence", 0) >= 0.6]
    review_signals = [s for s in signals if s.get("confidence", 0) < 0.6]

    signals_text = _format_signals_for_llm(signals)

    system_prompt = """You are the chief intelligence officer of MOSAIC - a clinical trial research integrity system.
    Your job is to compile a professional executive intelligence brief from the signals generated by specialist AI agents.

    BRIEF FORMAT:
    1. EXECUTIVE SUMMARY - 2-3 sentences summarizing the most critical findings
    2. SIGNAL BY PRIORITY - each signal as a numbered item with:
        - What was found
        - Why it matters
        - What action to take
    3. SIGNALS REQUIRING HUMAN REVEIW - list any low-confidence signals
    4. PIPELINE HEALTH - note any issues or errors during the run

    TONE: Professional, factual, actionable. Write as if briefing a senior compliance officer or investigative jounalist.
    Be Specific - include NCT IDs, sponsor names and exact timeframes. 
    """

    human_prompt = f"""
        ANALYSIS TASK: {task}
        SIGNALS FOUND BY AGENTS: {signals_text}
        HIGH CONFIDENCE SIGNALS: {len(high_confidence_signals)}
        SIGNALS REQUIRING REVIEW: {len(review_signals)}
        AGENTS ACTIVATED: {', '.join(agents_activated)}

        Please compile the final intelligence brief now.
    """

    try:
        response = llm.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=human_prompt)
            ]
        )

        final_brief = response.content
        logger.info(
            f"Brief compiled successfully | signals_included = {len(signals)} | brief_length={len(final_brief)} chars")

    except Exception as e:
        logger.error(f"LLM Brief compilation failed | error = {e}")
        final_brief = _fallback_brief(signals, agents_activated, task)

    return {
        "final_brief": final_brief,
        "run_complete": True,
        "total_signals": len(signals),
        "signals_requiring_review": len(review_signals),
        "agents_activated": agents_activated
    }


def _format_signals_for_llm(signals: list[SignalOutput]) -> str:
    if not signals:
        return "No signals generated."

    lines = []

    for i, signal in enumerate(signals, start=1):
        lines.append(f"SIGNAL {i}:")
        lines.append(f"Agent: {signal.get('agent', 'unknown')}")
        lines.append(f"Type: {signal.get('signal_type', 'unknown')}")
        lines.append(f"NCT ID: {signal.get('nct_id', 'N/A')}")
        lines.append(f"Confidence: {signal.get('confidence', 0.0):.2f}")
        lines.append(f"Summary: {signal.get('summary', '')}")
        lines.append("")

    return "\n".join(lines)


def _fallback_brief(signals: list, agents_activated: list, task: str) -> str:
    lines = [
        "**EXECUTIVE SUMMARY:**",
        f"Analysis Complete: {len(signals)} signal(s) detected.",
        "",
        "**SIGNALS BY PRIORITY:**",
        "",
    ]

    for i, signal in enumerate(signals, start=1):
        lines.append(
            f"{i}. **{signal.get('nct_id', 'Unknown')} - {signal.get('signal_type', 'Unknown')}:**")
        lines.append(f"{signal.get('summary', 'No summary available.')}")
        lines.append(
            f"Confidence: {signal.get('confidence', 0.0):.2f} | Agent: {signal.get('agent', 'unknown')}")
        lines.append("")

    lines.append(f"**AGENTS ACTIVATED:** {', '.join(agents_activated)}")
    lines.append("\n*Note: This brief was generated without LLM assistance due to a temporory error. Please review raw signals directly.")

    return '\n'.join(lines)
